module.exports = [
  'Controller',
  'Flasher',
  'Fliquidator',
  'FujiAdmin',
  'FujiERC1155',
  'ProviderAave',
  'ProviderCompound',
  'ProviderDYDX',
  'ProviderIronBank',
  'VaultETHDAI',
  'VaultETHUSDC',
  'VaultETHUSDT',
  'VaultHarvester',
];
