import { DEPLOYMENT, DEPLOYMENT_TYPES, CHAIN_NAME, CHAIN_NAMES } from 'consts/globals';
import * as core from './vaults-core';
import * as fuse from './vaults-fuse';
import * as fantom from './vaults-fantom';

const BORROW_IDS =
  CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.CORE
    ? core.BORROW_IDS
    : CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.FUSE
    ? fuse.BORROW_IDS
    : fantom.BORROW_IDS;

const COLLATERAL_IDS =
  CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.CORE
    ? core.COLLATERAL_IDS
    : CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.FUSE
    ? fuse.COLLATERAL_IDS
    : fantom.COLLATERAL_IDS;

const VAULTS_ADDRESS =
  CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.CORE
    ? core.VAULTS_ADDRESS
    : CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.FUSE
    ? fuse.VAULTS_ADDRESS
    : fantom.VAULTS_ADDRESS;

const VAULTS =
  CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.CORE
    ? core.VAULTS
    : CHAIN_NAME === CHAIN_NAMES.CORE && DEPLOYMENT === DEPLOYMENT_TYPES.FUSE
    ? fuse.VAULTS
    : fantom.VAULTS;

export { VAULTS_ADDRESS, BORROW_IDS, COLLATERAL_IDS, VAULTS };
